# language: python
# python:
#   - "3.8"
# sudo: required

# services:
#   - docker

# before_install:
#   - echo 'test'
#   # install heroku CLI
#   - wget -qO- https://toolbelt.heroku.com/install.sh | sh
#   - heroku login
#   - echo "machine api"
#   - heroku container:login

# script:
#   # - docker build -t cisaia/apisimplon:latest . 
#   # - docker tag cisaia/apisimplon registry.heroku.com/$HEROKU_APP_NAME/web
#   - docker tag cisaia/apisimplon registry.heroku.com/travis-testies/web

# deploy:
#   provider: script
#   script: 
#     # docker push cisaia/apisimplon;

#     # docker push registry.heroku.com/$HEROKU_APP_NAME/web;
#     # heroku container:push web --app $HEROKU_APP_NAME
#     heroku container:push web --app travis-testies
#     # heroku container:release web --app $HEROKU_APP_NAME
#     heroku container:release web --app travis-testies
#   on:
#     branch: master

language: python
python:
  - "3.8"
sudo: required

services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  - HEROKU_API_KEY=$HEROKU_PASSWORD heroku container:login
  - heroku container:push web --app $HEROKU_APP_NAME
  - heroku container:release web --app $HEROKU_APP_NAME
